---
# tasks file for student.myenv

- name: check myenv_user default
  fail: 
    msg: You must specify the variable 'myenv_user' to use this role!
  when: "myenv_user == ''"

- name: Install {{ myenv_packages }} package
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ myenv_packages }}"

- name: copy propile.png
  copy:
    src: profile.png
    dest: "~{{ myenv_user }}/profile.png"

- name: "Insert alias tree='tree -C'"
  lineinfile:
    dest: "~{{ myenv_user }}/.bashrc"
    line: alias tree='tree -C'

- name: Install mkcd.sh.j2 template
  template:
    src: mkcd.sh.j2  
    dest: /etc/profile.d/mkcd.sh
    owner: root
    group: root
    mode: 0644
