---
- name: Install custom fact 
  hosts: lamp
  vars:
    custom_file: custom.fact
    remote_dir: /etc/ansible/facts.d 

  tasks:
    - name: "Create remote directory"
      file:
        state: directory
        recurse: true
        path: "{{ remote_dir }}"    

    - name: "Install custom fact file"
      copy:
        src: "{{ custom_file }}"
        dest: "{{ remote_dir }}"
