---
- name: first play
  hosts: webservers
  remote_user: devops
  become: true #or yes
  tasks:
    - name: First task
      yum:
        name: httpd
        status: present

    - name: Second task
      service:
        name: httpd
        enabled: true

- name: second play
  hosts: dbservers
  tasks:
    - service:
        name: mariadb
        enabled: true

    
