---
- name: Demo2 playbook
  hosts: webservers
  tasks: 
    - name: Web server is enabled   #Task name을 지정하여 디버깅시 추적
      service:            #module name
        name: httpd
        enabled: true

    - name: NTP server is enabled
      service:
        name: chronyd
        enabled: true

    - name: Postfix is enabled
      service:
        name: postfix
        enabled: true
