---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb


  tasks:
    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes        # error가 발생해도 return 하지 않음

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest

    


